const FEED='https://market-edge-lab.darkbishop43.workers.dev/api/state';
const COINBASE='https://api.coinbase.com/v2/prices';
const EXCHANGE='https://api.exchange.coinbase.com/products';
const GAMMA='https://gamma-api.polymarket.com';
const C=window.SIBLING_CONFIG||{};
const E=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'$'+Number(n||0).toFixed(2);
const pct=n=>(Number(n||0)*100).toFixed(3)+'%';
const cent=n=>(Number(n||0)*100).toFixed(1)+'¢';
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
let snapshot=null,lastLivePriceAt=null,prev={BTC:null,ETH:null};
let directional={opportunities:[],seen:0,rejected:0,updatedAt:null,error:null};
const stateKey='nfe_market_edge_'+(C.key||'sibling')+'_v1';
function loadLocal(){try{return JSON.parse(localStorage.getItem(stateKey))||null}catch{return null}}
function defaultLocal(){return{mode:'PAPER_ONLY',lab:C.key||'sibling',balance:100,realizedPnl:0,positions:[],ledger:[],trades:0,createdAt:new Date().toISOString()}}
let local=loadLocal()||defaultLocal();
function saveLocal(){localStorage.setItem(stateKey,JSON.stringify(local))}
function t(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?'—':d.toLocaleString()}
function dur(ms){const s=Math.round(Number(ms||0)/1000);if(!s)return'—';return s<60?s+' sec':Math.floor(s/60)+'m '+s%60+'s'}
function detail(a,b){return `<div class="detail"><span>${esc(a)}</span><b>${esc(b)}</b></div>`}
function rawOpps(s){const a=s?.opportunities||s?.eligible||s?.candidates||[];return Array.isArray(a)?a:[]}
function score(o){return Number(o.score??o.signalScore??0)}
function edge(o){return Number(o.edge??0)}
function move(o){return Number(o.move??o.assetMove??o.btcMove??o.ethMove??0)}
function question(o){return o.question||o.title||o.marketQuestion||o.slug||'Unknown market'}
function asset(o){return o.asset||(/ethereum|\beth\b/i.test(question(o))?'ETH':'BTC')}
function price(o){return Number(o.yesPrice??o.yes??o.price??0)}
function marketId(o){return String(o.id??o.marketId??o.conditionId??o.slug??question(o))}
function side(o){if(o.side)return o.side;if(o.bear===true)return'BELOW';const q=question(o).toLowerCase();const dn=/\b(below|lower|under|down|fall|drop|decrease)\b/.test(q);const up=/\b(above|higher|over|up|rise|gain|increase)\b/.test(q);return dn&&!up?'BELOW':up&&!dn?'ABOVE':'UNKNOWN'}
function normalizedBaseline(){return rawOpps(snapshot).map(o=>({...o,side:side(o),source:o.source||'BASELINE_FEED'}))}
function opportunities(){const m=new Map();for(const o of [...normalizedBaseline(),...(directional.opportunities||[])]){const id=marketId(o);if(!id)continue;const old=m.get(id);if(!old||score(o)>score(old))m.set(id,o)}return [...m.values()].sort((a,b)=>score(b)-score(a))}
function inferDirection(q){q=String(q||'').toLowerCase();const a=q.includes('bitcoin')||/\bbtc\b/.test(q)?'BTC':q.includes('ethereum')||/\beth\b/.test(q)?'ETH':null;if(!a)return null;const dn=/\b(below|lower|under|down|fall|drop|decrease)\b/.test(q);const up=/\b(above|higher|over|up|rise|gain|increase)\b/.test(q);if(dn===up)return null;return{asset:a,side:dn?'BELOW':'ABOVE'}}
function parsePrices(m){try{const p=typeof m.outcomePrices==='string'?JSON.parse(m.outcomePrices):m.outcomePrices;if(!Array.isArray(p)||p.length<2)return null;const yes=Number(p[0]),no=Number(p[1]);if(!Number.isFinite(yes)||!Number.isFinite(no))return null;return{yes,no}}catch{return null}}
function eligibleMarket(m,ev,p){if(m.closed===true||ev.closed===true||m.active===false||ev.active===false||m.acceptingOrders===false)return false;const end=m.endDate||m.endDateIso||ev.endDate||ev.endDateIso;if(end){const x=Date.parse(end);if(Number.isFinite(x)&&x<=Date.now())return false}return !(p.yes<=.01||p.yes>=.99||p.no<=.01||p.no>=.99)}
async function gammaJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('Gamma '+r.status);return r.json()}
async function discoverQuery(q){const s=await gammaJson(`${GAMMA}/public-search?q=${encodeURIComponent(q)}`);const evs=(s.events||[]).slice(0,14);const ds=await Promise.all(evs.map(async e=>{try{return await gammaJson(`${GAMMA}/events/${e.id}`)}catch{return null}}));return ds.filter(Boolean)}
async function fetchDirectional(){try{const qs=['bitcoin below','bitcoin down','BTC below','ethereum below','ethereum down','ETH below'];const groups=await Promise.all(qs.map(discoverQuery));const map=new Map();let seen=0,rejected=0;const moves=snapshot?.moves||{};for(const ev of groups.flat()){for(const m of(ev.markets||[])){seen++;const q=[ev.title,m.question,m.slug].filter(Boolean).join(' — '),dir=inferDirection(q),p=parsePrices(m);if(!dir||dir.side!=='BELOW'||!p||!eligibleMarket(m,ev,p)){rejected++;continue}const id=String(m.id||m.conditionId||m.slug);const mv=Number(moves[dir.asset]||0),directionalMove=-mv,fair=clamp(p.yes+directionalMove*18,.02,.98),ed=fair-p.yes,sc=clamp(.5+ed*4,0,1);map.set(id,{id,question:q,asset:dir.asset,side:'BELOW',bear:true,yes:p.yes,no:p.no,move:mv,fair,edge:ed,score:sc,source:'DIRECTIONAL_DISCOVERY',volume:Number(m.volumeNum||m.volume||0),liquidity:Number(m.liquidityNum||m.liquidity||0),endDate:m.endDate||ev.endDate||null})}}directional={opportunities:[...map.values()],seen,rejected,updatedAt:new Date().toISOString(),error:null};render()}catch(e){directional.error=String(e?.message||e);directional.updatedAt=new Date().toISOString();render()}}
function render(){E('bal').textContent=money(local.balance);E('pnl').textContent=(local.realizedPnl<0?'-':'')+money(Math.abs(local.realizedPnl));E('pnl').className='val '+(local.realizedPnl<0?'bad':local.realizedPnl>0?'good':'');E('closed').textContent=local.trades||0;E('openCount').textContent=(local.positions||[]).length;const s=snapshot||{},os=opportunities(),above=os.filter(o=>side(o)==='ABOVE').length,below=os.filter(o=>side(o)==='BELOW').length;E('eligible').textContent=os.length;E('rejected').textContent=(s.rejectedCount??0)+(directional.rejected||0);E('examined').textContent=(s.seenCount??0)+(directional.seen||0);renderOpps(os);renderPositions();renderTrades();E('run').textContent='Shared snapshot: '+t(s.lastRunAt||s.updatedAt)+` · ${above} ABOVE · ${below} BELOW`;const age=s.lastRunAt?Date.now()-Date.parse(s.lastRunAt):Infinity;E('cloud').innerHTML=age<=600000?'<b class="good">LIVE SHARED MARKET FEED · ABOVE + BELOW · PAPER ONLY</b>':age<=1800000?'<b style="color:var(--yellow)">STALE SHARED FEED · ABOVE + BELOW</b>':'<b class="bad">SHARED FEED OFFLINE</b>';E('dot').className='dot '+(age<=600000?'':age<=1800000?'warnDot':'badDot')}
function renderOpps(os=opportunities()){const list=os.slice(0,16);if(!list.length){E('opps').innerHTML='<div class="empty">No eligible opportunities in the current shared snapshot.</div>';return}E('opps').innerHTML=list.map((o,i)=>{const a=C.analyze?C.analyze(o,os,i):{label:'WATCH',confidence:Math.round(score(o)*100),html:''},sd=side(o);return `<div class="opp"><div class="oppHead"><div class="q"><span class="sideBadge ${sd==='BELOW'?'below':'above'}">${esc(sd)}</span>${esc(question(o))}</div><div><div class="scoreBadge"><small>SCORE</small>${score(o).toFixed(2)}</div><div class="decisionBadge" style="margin-top:6px"><small>${esc(C.decisionLabel||'VIEW')}</small>${esc(a.label)}</div></div></div><div class="meta"><span>${esc(asset(o))}</span><span>${esc(sd)}</span><span>move ${pct(move(o))}</span><span>YES ${cent(price(o))}</span><span>edge ${pct(edge(o))}</span></div><div class="bar"><div class="fill" style="width:${Math.max(0,Math.min(100,score(o)*100))}%"></div></div>${a.html||''}</div>`}).join('')}
function renderPositions(){const ps=local.positions||[];E('pos').innerHTML=ps.length?ps.map(p=>`<div class="trade"><div><div class="trade-title"><span class="sideBadge ${p.side==='BELOW'?'below':'above'}">${esc(p.side||'—')}</span>${esc(p.question)}</div><div class="trade-meta">${esc(p.asset)} · entry ${cent(p.entry)} · ${t(p.ts)}</div></div><div class="pnl">OPEN</div></div>`).join(''):'<div class="empty">None</div>'}
function renderTrades(){const xs=(local.ledger||[]).filter(x=>x.type==='PAPER_EXIT').slice().reverse();E('trades').innerHTML=xs.length?xs.map((x,i)=>`<div class="trade" data-i="${i}"><div><div class="trade-title"><span class="sideBadge ${x.side==='BELOW'?'below':'above'}">${esc(x.side||'—')}</span>${esc(x.question)}</div><div class="trade-meta">${t(x.ts)} · ${esc(x.reason||'exit')}</div></div><div class="pnl ${Number(x.pnl)>=0?'good':'bad'}">${Number(x.pnl)>=0?'+':''}${money(x.pnl)}</div></div>`).join(''):'<div class="empty">No closed sibling paper trades yet.</div>';[...E('trades').querySelectorAll('.trade')].forEach((n,i)=>n.onclick=()=>openTrade(xs[i]))}
function openTrade(x){E('modalTitle').textContent='Paper Trade · '+(Number(x.pnl)>=0?'Gain':'Loss');E('modalBody').innerHTML=`<div class="q">${esc(x.question)}</div><div class="detail-grid">${detail('Asset',x.asset||'—')}${detail('Direction',x.side||'—')}${detail('Stake',money(x.stake))}${detail('Entry time',t(x.entryTs))}${detail('Exit time',t(x.ts))}${detail('Entry YES',cent(x.entry))}${detail('Exit YES',cent(x.exit))}${detail('Entry score',Number(x.score||0).toFixed(3))}${detail('Entry edge',pct(x.edge))}${detail('Held',dur(x.heldMs))}${detail('Exit reason',x.reason||'—')}${detail('Realized P/L',(Number(x.pnl)>=0?'+':'')+money(x.pnl))}${detail('Market ID',x.marketId||'—')}</div><div class="note">Sibling evidence only. Direction records the actual contract being evaluated. BELOW opportunities come from actual downside contracts discovered from Polymarket; the lab does not manufacture a BELOW trade by blindly using 1 − YES.</div>`;E('modal').classList.add('open')}
async function fetchState(){try{const r=await fetch(FEED,{cache:'no-store'});if(!r.ok)throw Error(r.status);snapshot=await r.json();render();await fetchDirectional()}catch(e){E('cloud').innerHTML='<b class="bad">SHARED FEED ERROR</b>';E('dot').className='dot badDot'}}
async function spot(a){const r=await fetch(`${COINBASE}/${a}-USD/spot`,{cache:'no-store'});const j=await r.json();return Number(j.data.amount)}
async function live(){try{for(const a of['BTC','ETH']){const v=await spot(a),el=E(a.toLowerCase());el.textContent=money(v);if(prev[a]!=null&&v!==prev[a]){el.style.color=v>prev[a]?'var(--green)':'var(--red)';setTimeout(()=>el.style.color='',500)}prev[a]=v}lastLivePriceAt=new Date().toISOString();E('priceRun').textContent='Live display prices: '+new Date().toLocaleTimeString()+' · refreshes every 10 sec'}catch{}}
async function trend(a){try{const r=await fetch(`${EXCHANGE}/${a}-USD/stats`,{cache:'no-store'}),j=await r.json();const ch=(Number(j.last)-Number(j.open))/Number(j.open),el=E(a.toLowerCase()+'Dir');el.textContent=`${ch>=0?'▲':'▼'} ${(ch*100).toFixed(2)}% · 24h`;el.className='direction '+(ch>=0?'dirUp':'dirDown');const cr=await fetch(`${EXCHANGE}/${a}-USD/candles?granularity=3600`,{cache:'no-store'}),cs=(await cr.json()).slice(0,24).reverse(),vals=cs.map(x=>Number(x[4]));if(vals.length){const lo=Math.min(...vals),hi=Math.max(...vals),pts=vals.map((v,i)=>`${i*(180/(vals.length-1||1))},${38-(v-lo)/(hi-lo||1)*34}`).join(' ');const svg=E(a.toLowerCase()+'Spark');svg.querySelector('polyline').setAttribute('points',pts);svg.className='spark '+(ch>=0?'dirUp':'dirDown')}}catch{}}
function exportEvidence(){const payload={exportedAt:new Date().toISOString(),source:C.title||C.key,mode:'PAPER_ONLY',displayLivePrices:{capturedAt:lastLivePriceAt,btc:E('btc').textContent,eth:E('eth').textContent},sharedMarketSnapshot:snapshot,directionalDiscovery:directional,mergedOpportunities:opportunities(),independentSiblingState:local};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=(C.key||'sibling')+'-evidence-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
E('exportBtn').onclick=exportEvidence;E('closeBtn').onclick=()=>E('modal').classList.remove('open');E('modal').onclick=e=>{if(e.target===E('modal'))E('modal').classList.remove('open')};saveLocal();render();fetchState();live();trend('BTC');trend('ETH');setInterval(fetchState,30000);setInterval(live,10000);setInterval(()=>{trend('BTC');trend('ETH')},60000);
