function renderStats(){const s=stats(filtered),manual=filtered.filter(r=>r.source==='FOUNDER_MANUAL').length;const vals=[['SAMPLE',filtered.length+' / 342',''],['NET P/L',money(s.net),s.net>=0?'pos':'neg'],['GROSS P/L',money(s.gross),s.gross>=0?'pos':'neg'],['FEES',money(s.fees),'neg'],['WIN RATE',pct(s.wr),''],['MAX DRAWDOWN',money(s.maxdd),'neg'],['W / L / F',`${s.wins} / ${s.losses} / ${s.flats}`,''],['FOUNDER ROWS',manual,''],['AUTO ROWS',filtered.length-manual,''],['DATA MODE','RAW PROVIDER',''],['NFE SCORE','UNKNOWN',''],['LOGICAL COUNT','UNKNOWN','']];$('#stats').innerHTML=vals.map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="v ${x[2]}">${x[1]}</div></div>`).join('')}
function setup(c){const dpr=devicePixelRatio||1,rect=c.getBoundingClientRect();c.width=Math.max(1,rect.width*dpr);c.height=Math.max(1,rect.height*dpr);const g=c.getContext('2d');g.scale(dpr,dpr);return [g,rect.width,rect.height]}
function axes(g,w,h,min,max){g.strokeStyle='#27405d';g.lineWidth=1;g.beginPath();g.moveTo(42,10);g.lineTo(42,h-28);g.lineTo(w-10,h-28);g.stroke();g.fillStyle='#7890aa';g.font='10px system-ui';for(let i=0;i<5;i++){const v=max-(max-min)*i/4,y=14+(h-46)*i/4;g.fillText(v.toFixed(2),3,y+3);g.strokeStyle='#16293d';g.beginPath();g.moveTo(42,y);g.lineTo(w-10,y);g.stroke()}}
function lineChart(id,series,opt={}){const c=$(id),[g,w,h]=setup(c);g.clearRect(0,0,w,h);if(!series.length){g.fillStyle='#8196ad';g.fillText('NO DATA',20,30);return}const ys=series.map(x=>x.y);let min=Math.min(0,...ys),max=Math.max(0,...ys);if(max===min){max+=1;min-=1}axes(g,w,h,min,max);const X=i=>42+(w-55)*(series.length<2?0:i/(series.length-1)),Y=v=>12+(h-42)*(max-v)/(max-min);g.strokeStyle=opt.color||'#5dd6ff';g.lineWidth=2;g.beginPath();series.forEach((p,i)=>i?g.lineTo(X(i),Y(p.y)):g.moveTo(X(i),Y(p.y)));g.stroke();series.forEach((p,i)=>{if(series.length<120||i%Math.ceil(series.length/120)===0){g.fillStyle=p.c||opt.color||'#5dd6ff';g.fillRect(X(i)-1.5,Y(p.y)-1.5,3,3)}})}
function bars(id,items){const c=$(id),[g,w,h]=setup(c);g.clearRect(0,0,w,h);if(!items.length){g.fillStyle='#8196ad';g.fillText('NO DATA',20,30);return}const vals=items.map(x=>x.v),min=Math.min(0,...vals),max=Math.max(0,...vals);axes(g,w,h,min,max);const z=12+(h-42)*(max)/(max-min||1),bw=(w-58)/items.length*.72;items.forEach((x,i)=>{const xc=44+(w-58)*(i+.5)/items.length,y=12+(h-42)*(max-x.v)/(max-min||1);g.fillStyle=x.v>=0?'#55e39f':'#ff6b78';g.fillRect(xc-bw/2,Math.min(y,z),bw,Math.max(1,Math.abs(z-y)));g.fillStyle='#94a8c0';g.font='9px system-ui';g.save();g.translate(xc,h-24);g.rotate(-.55);g.fillText(x.k,0,0);g.restore()})}
function scatter(id,rows){const c=$(id),[g,w,h]=setup(c);g.clearRect(0,0,w,h);if(!rows.length)return;const xs=rows.map(r=>num(r.entry_price_dollars)),ys=rows.map(r=>num(r.realized_pnl_with_fees_dollars)),minY=Math.min(0,...ys),maxY=Math.max(0,...ys);axes(g,w,h,minY,maxY);rows.forEach((r,i)=>{const x=42+(w-55)*num(r.entry_price_dollars),y=12+(h-42)*(maxY-num(r.realized_pnl_with_fees_dollars))/(maxY-minY||1);g.fillStyle=r.result==='WIN'?'#55e39faa':r.result==='LOSS'?'#ff6b78aa':'#8395aa';g.beginPath();g.arc(x,y,Math.max(2,Math.min(7,2+Math.sqrt(num(r.quantity_fp)))),0,Math.PI*2);g.fill()})}
function cumulative(){let c=0;return filtered.map(r=>{c+=num(r.realized_pnl_with_fees_dollars);return{y:c,c:r.result==='WIN'?'#55e39f':r.result==='LOSS'?'#ff6b78':'#8899aa'}})}
function drawdown(){let c=0,p=0;return filtered.map(r=>{c+=num(r.realized_pnl_with_fees_dollars);p=Math.max(p,c);return{y:c-p,c:'#ff6b78'}})}
function group(key){const m={};filtered.forEach(r=>{const k=key(r);(m[k]??=[]).push(r)});return Object.entries(m).map(([k,v])=>({k,v:v.reduce((s,r)=>s+num(r.realized_pnl_with_fees_dollars),0),n:v.length})).sort((a,b)=>b.v-a.v)}
function renderStrip(){const el=$('#strip');el.innerHTML=filtered.map((r,i)=>`<div class="dot ${r.result.toLowerCase()} ${r.source==='FOUNDER_MANUAL'?'manual':''}" title="#${r.row_index} ${r.market_ticker} ${r.result} ${money(r.realized_pnl_with_fees_dollars)}" data-i="${i}"></div>`).join('');el.querySelectorAll('.dot').forEach(x=>x.onclick=()=>inspect(filtered[+x.dataset.i]))}
function inspect(r){selected=r;const fields=[['Provider row',r.row_index],['Source tag',r.source],['Ticker',r.market_ticker],['Asset',r.asset],['Side',r.side.toUpperCase()],['Quantity',r.quantity_fp],['Entry',money(r.entry_price_dollars)],['Exit',money(r.exit_price_dollars)],['Gross P/L',money(r.realized_pnl_without_fees_dollars)],['Open fee',money(r.open_fees_dollars)],['Close fee',money(r.close_fees_dollars)],['Net P/L',money(r.realized_pnl_with_fees_dollars)],['Opened',r.open_timestamp],['Closed',r.close_timestamp],['NFE score','UNKNOWN'],['Series / attempt','UNKNOWN']];$('#inspector').innerHTML=fields.map(([k,v])=>`<div class="kv"><b>${k}</b>${v}</div>`).join('')}
function table(){const rows=filtered.slice().reverse();$('#tbody').innerHTML=rows.map((r,i)=>`<tr data-row="${r.row_index}"><td>${r.row_index}</td><td>${r.close_timestamp.replace('T',' ').slice(0,19)}</td><td>${r.asset}</td><td>${r.side.toUpperCase()}</td><td>${r.quantity_fp}</td><td>${Number(r.entry_price_dollars).toFixed(3)}</td><td>${Number(r.exit_price_dollars).toFixed(3)}</td><td class="${r.result==='WIN'?'pos':r.result==='LOSS'?'neg':''}">${money(r.realized_pnl_with_fees_dollars)}</td><td class="${r.source==='FOUNDER_MANUAL'?'source-manual':''}">${r.source}</td></tr>`).join('');$('#tbody').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>inspect(RAW.find(r=>r.row_index==tr.dataset.row)))}
function histogram(){const vals=filtered.map(r=>num(r.realized_pnl_with_fees_dollars));if(!vals.length){bars('#dist',[]);return}let mn=Math.min(...vals),mx=Math.max(...vals);if(mn===mx){mn-=.5;mx+=.5}const n=14,bins=Array.from({length:n},(_,i)=>({k:'',v:0}));vals.forEach(v=>{let i=Math.min(n-1,Math.max(0,Math.floor((v-mn)/(mx-mn)*n)));bins[i].v++});bins.forEach((b,i)=>{const a=mn+(mx-mn)*i/n,z=mn+(mx-mn)*(i+1)/n;b.k=`${a.toFixed(2)}…${z.toFixed(2)}`});bars('#dist',bins)}
function render(){renderStats();histogram();lineChart('#cum',cumulative());renderStrip();bars('#assets',group(r=>r.asset));bars('#sideChart',group(r=>r.side.toUpperCase()));scatter('#scatter',filtered);bars('#hours',group(r=>String(dt(r.open_timestamp).getHours()).padStart(2,'0')+':00').sort((a,b)=>a.k.localeCompare(b.k)));const s=stats(filtered);bars('#econ',[{k:'GROSS',v:s.gross},{k:'FEES',v:-s.fees},{k:'NET',v:s.net}]);lineChart('#dd',drawdown(),{color:'#ff6b78'});table();if(!selected&&filtered.length)inspect(filtered[filtered.length-1]);$('#sample').textContent=`${filtered.length} provider rows shown`}
function boot(){RAW=hydrateRows();if(RAW.length!==342)throw new Error('Provider row integrity failure: '+RAW.length);fillFilters();['asset','side','source','result','from','to'].forEach(id=>$('#'+id).onchange=apply);$('#q').oninput=apply;$('#reset').onclick=reset;apply();addEventListener('resize',()=>render())}try{boot()}catch(e){document.body.innerHTML='<div style="padding:30px;color:#ff6b78;background:#071019;font:16px system-ui"><h1>OBSERVATORY DATA LOAD FAILED</h1><pre>'+e.message+'</pre></div>'}
