let RAW=[];
const PROVIDER_COLUMNS=['subtrader_id','type','quantity_fp','market_ticker','side','entry_price_dollars','exit_price_dollars','open_fees_dollars','close_fees_dollars','realized_pnl_without_fees_dollars','realized_pnl_with_fees_dollars','close_timestamp','open_timestamp'];
const VARIABLE_COLUMNS=['quantity_fp','market_ticker','side','entry_price_dollars','exit_price_dollars','open_fees_dollars','close_fees_dollars','realized_pnl_without_fees_dollars','realized_pnl_with_fees_dollars','close_timestamp','open_timestamp'];
function hydrateRows(){const packed=[...(window.__ME_DATA||[])];return packed.map((a,idx)=>{const r={subtrader_id:'471bb73c-2bff-4b56-88ad-5aebe334461b',type:'trade'};VARIABLE_COLUMNS.forEach((k,i)=>r[k]=a[i]);r.row_index=idx+1;const m=r.market_ticker.match(/^KX([A-Z0-9]+?)15M-/);r.asset=m?m[1]:'UNKNOWN';r.source=(r.market_ticker==='KXNEAR15M-26SEP292215-15'&&r.side==='yes')?'FOUNDER_MANUAL':'AUTO_BASELINE';const n=Number(r.realized_pnl_with_fees_dollars);r.result=n>1e-12?'WIN':n<-1e-12?'LOSS':'FLAT';return r})}
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=n=>n==null?'UNKNOWN':(n<0?'-$':'$')+Math.abs(n).toFixed(2);const pct=n=>Number.isFinite(n)?(n*100).toFixed(1)+'%':'UNKNOWN';
const dt=s=>new Date(s);const num=x=>Number(x)||0;const fee=r=>num(r.open_fees_dollars)+num(r.close_fees_dollars);
let filtered=[],selected=null;
function fillFilters(){const assets=[...new Set(RAW.map(r=>r.asset))].sort(); $('#asset').innerHTML='<option>ALL</option>'+assets.map(x=>`<option>${x}</option>`).join('');}
function getFilters(){return {asset:$('#asset').value,side:$('#side').value,source:$('#source').value,result:$('#result').value,q:$('#q').value.trim().toUpperCase(),from:$('#from').value,to:$('#to').value}}
function apply(){const f=getFilters();filtered=RAW.filter(r=>(f.asset==='ALL'||r.asset===f.asset)&&(f.side==='ALL'||r.side===f.side)&&(f.source==='ALL'||r.source===f.source)&&(f.result==='ALL'||r.result===f.result)&&(!f.q||r.market_ticker.includes(f.q))&&(!f.from||dt(r.open_timestamp)>=new Date(f.from+'T00:00:00'))&&(!f.to||dt(r.open_timestamp)<=new Date(f.to+'T23:59:59'))).sort((a,b)=>dt(a.close_timestamp)-dt(b.close_timestamp));render();}
function reset(){['asset','side','source','result'].forEach(id=>$('#'+id).value='ALL');['q','from','to'].forEach(id=>$('#'+id).value='');apply()}
function stats(rows){const net=rows.reduce((s,r)=>s+num(r.realized_pnl_with_fees_dollars),0),gross=rows.reduce((s,r)=>s+num(r.realized_pnl_without_fees_dollars),0),fees=rows.reduce((s,r)=>s+fee(r),0);const wins=rows.filter(r=>r.result==='WIN').length,losses=rows.filter(r=>r.result==='LOSS').length,flats=rows.length-wins-losses;let c=0,peak=0,maxdd=0;rows.forEach(r=>{c+=num(r.realized_pnl_with_fees_dollars);peak=Math.max(peak,c);maxdd=Math.min(maxdd,c-peak)});return{net,gross,fees,wins,losses,flats,wr:(wins+losses)?wins/(wins+losses):NaN,maxdd}}
