from pathlib import Path
p=Path('market-edge-lab/real/baseline/founder-terminal.html')
s=p.read_text()
css='''\n/* THESIS_TRAFFIC_LIGHTS_V1 — presentation only */\n.thesisLights{display:flex;gap:7px;flex-wrap:wrap;margin:7px 0}.thesisLamp{display:flex;align-items:center;gap:6px;border:1px solid #26394b;background:#071019;padding:6px 9px;font-size:9px;font-weight:900;letter-spacing:.035em;opacity:.28;filter:saturate(.35);transition:opacity .15s,filter .15s,box-shadow .15s,border-color .15s}.thesisLamp .dot{font-size:15px;line-height:1}.thesisLamp.green .dot{color:var(--green)}.thesisLamp.yellow .dot{color:var(--amber)}.thesisLamp.red .dot{color:var(--red)}.thesisLamp.active{opacity:1;filter:none;border-color:#5a7187;box-shadow:0 0 12px rgba(100,168,255,.12)}.thesisLamp.green.active{box-shadow:0 0 12px rgba(38,211,129,.18)}.thesisLamp.yellow.active{box-shadow:0 0 12px rgba(255,193,66,.18)}.thesisLamp.red.active{box-shadow:0 0 12px rgba(255,77,90,.18)}.thesisNoLive{font-size:9px;font-weight:900;color:#71869a;letter-spacing:.05em;margin-top:3px}.thesisMetrics4{display:grid;grid-template-columns:repeat(4,minmax(110px,1fr));gap:1px;background:var(--line);margin-top:7px}.thesisMetrics4>div{background:#08111a;padding:5px}@media(max-width:700px){.thesisLamp{flex:1 1 100%}.thesisMetrics4{grid-template-columns:repeat(2,minmax(100px,1fr))}}\n'''
if 'THESIS_TRAFFIC_LIGHTS_V1' not in s:
    s=s.replace('</style>',css+'\n</style>',1)
old="function paintThesis(){const ps=A(obs.hold?.positions);document.querySelectorAll('.holdCard').forEach(card=>card.querySelector('.thesisStrip')?.remove());for(const p of ps){const card=[...document.querySelectorAll('.holdCard')].find(c=>String(c.querySelector('.holdTicker')?.textContent||'').trim()===String(p.ticker||''));if(!card)continue;const t=thesis(p),lc=t.light.toLowerCase();card.insertAdjacentHTML('beforeend','<div class=\"thesisStrip\"><div class=\"thesisTop\"><span class=\"thesisLight '+lc+'\">● '+t.light+'</span><span class=\"thesisReason\">'+E(t.reason)+'</span><span class=\"thesisExact\">EXACT TICKER ONLY</span></div><div class=\"thesisGrid\"><div><div class=\"holdK\">ENTRY SCORE</div><div class=\"holdV\">'+(t.entry===null?'—':t.entry.toFixed(3))+'</div></div><div><div class=\"holdK\">CURRENT '+E(p.side)+'</div><div class=\"holdV\">'+(t.same===null?'—':t.same.toFixed(3))+'</div></div><div><div class=\"holdK\">CHANGE SINCE ENTRY</div><div class=\"holdV\">'+(t.sameDelta===null?'—':(t.sameDelta>=0?'+':'')+t.sameDelta.toFixed(3))+'</div></div><div><div class=\"holdK\">CURRENT OPPOSITE</div><div class=\"holdV\">'+(t.opp===null?'—':t.opp.toFixed(3))+'</div></div><div><div class=\"holdK\">OPPOSITE CHANGE</div><div class=\"holdV\">NOT RETAINED</div></div></div><div class=\"thesisNote\">FOUNDER HEADS-UP ONLY · NO AUTO ACTION · NO EXIT / ENTRY / HOLD AUTHORITY</div></div>')}}"
new="function paintThesis(){const ps=A(obs.hold?.positions);document.querySelectorAll('.holdCard').forEach(card=>card.querySelector('.thesisStrip')?.remove());for(const p of ps){const card=[...document.querySelectorAll('.holdCard')].find(c=>String(c.querySelector('.holdTicker')?.textContent||'').trim()===String(p.ticker||''));if(!card)continue;const t=thesis(p),lc=t.light.toLowerCase(),lamp=(key,label)=>'<div class=\"thesisLamp '+key+' '+(lc===key?'active':'')+'\"><span class=\"dot\">●</span><span>'+label+'</span></div>';card.insertAdjacentHTML('beforeend','<div class=\"thesisStrip\"><div class=\"thesisLights\">'+lamp('green','THESIS INTACT')+lamp('yellow','THESIS WEAKENING')+lamp('red','OPPOSITE SIDE STRONGER')+'</div><div class=\"thesisTop\"><span class=\"thesisReason\">'+E(t.reason)+'</span><span class=\"thesisExact\">EXACT TICKER ONLY</span></div><div class=\"thesisMetrics4\"><div><div class=\"holdK\">ENTRY SCORE</div><div class=\"holdV\">'+(t.entry===null?'—':t.entry.toFixed(3))+'</div></div><div><div class=\"holdK\">CURRENT OWNED-SIDE SCORE</div><div class=\"holdV\">'+(t.same===null?'—':t.same.toFixed(3))+'</div></div><div><div class=\"holdK\">CURRENT OPPOSITE-SIDE SCORE</div><div class=\"holdV\">'+(t.opp===null?'—':t.opp.toFixed(3))+'</div></div><div><div class=\"holdK\">CHANGE SINCE ENTRY</div><div class=\"holdV\">'+(t.sameDelta===null?'—':(t.sameDelta>=0?'+':'')+t.sameDelta.toFixed(3))+'</div></div></div><div class=\"thesisNote\">FOUNDER HEADS-UP ONLY · NO AUTO ACTION · NO EXIT / ENTRY / HOLD AUTHORITY</div></div>')}}"
if old not in s: raise SystemExit('paintThesis anchor missing')
s=s.replace(old,new,1)
old2="else cards.innerHTML='<div class=\"holdEmpty\">NO LIVE OWNED POSITION</div>';const panel=$('holdObsPanel');if(panel)panel.classList.toggle('compactNoPos',!ps.length&&!state?.recentClosed)}"
new2="else cards.innerHTML='<div class=\"holdEmpty\"><div class=\"thesisLights\"><div class=\"thesisLamp green\"><span class=\"dot\">●</span><span>THESIS INTACT</span></div><div class=\"thesisLamp yellow\"><span class=\"dot\">●</span><span>THESIS WEAKENING</span></div><div class=\"thesisLamp red\"><span class=\"dot\">●</span><span>OPPOSITE SIDE STRONGER</span></div></div><div class=\"thesisNoLive\">NO LIVE THESIS TO EVALUATE</div><div class=\"thesisMetrics4\"><div><div class=\"holdK\">ENTRY SCORE</div><div class=\"holdV\">—</div></div><div><div class=\"holdK\">CURRENT OWNED-SIDE SCORE</div><div class=\"holdV\">—</div></div><div><div class=\"holdK\">CURRENT OPPOSITE-SIDE SCORE</div><div class=\"holdV\">—</div></div><div><div class=\"holdK\">CHANGE SINCE ENTRY</div><div class=\"holdV\">—</div></div></div><div class=\"thesisNote\">FOUNDER HEADS-UP ONLY · NO AUTO ACTION</div></div>';const panel=$('holdObsPanel');if(panel)panel.classList.toggle('compactNoPos',!ps.length&&!state?.recentClosed)}"
if old2 not in s: raise SystemExit('no-position anchor missing')
s=s.replace(old2,new2,1)
p.write_text(s)
print('THESIS_TRAFFIC_LIGHTS_PATCHED=YES')
