from pathlib import Path
p=Path('market-edge-lab/real/baseline/founder-terminal.html')
s=p.read_text()
css=r'''
/* THREE_LAYER_OBSERVABILITY_V1 — Founder heads-up only; zero execution authority */
.threeLayerWrap{padding:8px;overflow:auto}.threeHead{display:flex;align-items:center;gap:8px;margin-bottom:8px}.threeTitle{font-weight:900;letter-spacing:.09em;color:#fff}.threeSub{font-size:8px;color:var(--muted)}.runCards{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:7px;margin-bottom:9px}.runCard{border:1px solid #2c4054;background:#08121b;padding:9px}.runName{font-size:10px;font-weight:900;color:var(--gold);margin-bottom:6px}.runGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--line)}.runGrid>div{background:#071019;padding:5px}.runK{font-size:7px;color:#687d91;letter-spacing:.05em}.runV{font-size:10px;font-weight:900;margin-top:1px}.triTbl{width:100%;border-collapse:collapse;white-space:nowrap}.triTbl th{position:sticky;top:0;background:#0a1119;color:#60768d;text-align:right;font-size:8px;letter-spacing:.06em;padding:6px;border-bottom:1px solid var(--line);z-index:3}.triTbl th:first-child,.triTbl td:first-child{text-align:left}.triTbl td{text-align:right;padding:6px;border-bottom:1px solid #101b26;font-size:9px}.triGood{color:var(--green);font-weight:900}.triWarn{color:var(--amber);font-weight:900}.triBad{color:var(--red);font-weight:900}.triUnknown{color:#75889a}.thesisStrip{margin-top:8px;border:1px solid #2f465c;background:#071019;padding:8px}.thesisTop{display:flex;align-items:center;gap:8px}.thesisLight{font-size:15px;font-weight:900}.thesisLight.green{color:var(--green)}.thesisLight.yellow{color:var(--amber)}.thesisLight.red{color:var(--red)}.thesisReason{font-size:10px;font-weight:900}.thesisGrid{display:grid;grid-template-columns:repeat(5,minmax(95px,1fr));gap:1px;background:var(--line);margin-top:7px}.thesisGrid>div{background:#08111a;padding:5px}.thesisNote{margin-top:6px;color:var(--amber);font-size:8px;font-weight:900;letter-spacing:.05em}.thesisExact{margin-left:auto;color:#71869a;font-size:8px}
@media(max-width:900px){.runGrid{grid-template-columns:repeat(2,1fr)}.thesisGrid{grid-template-columns:repeat(2,1fr)}}
'''
if 'THREE_LAYER_OBSERVABILITY_V1' not in s:
    s=s.replace('</style>',css+'\n</style>',1)
old='<button data-tab="compare">LEDGER COMPARE</button><button data-tab="log">SYSTEM / EVENT LOG</button>'
new='<button data-tab="compare">LEDGER COMPARE</button><button data-tab="triage">THREE-LAYER</button><button data-tab="log">SYSTEM / EVENT LOG</button>'
if old not in s: raise SystemExit('tab anchor missing')
s=s.replace(old,new,1)
oldrender="function renderTab(){\n if(state.tab==='compare'&&typeof window.renderLedgerCompare==='function'){window.renderLedgerCompare();return}"
newrender="function renderTab(){\n if(state.tab==='triage'&&typeof window.renderThreeLayer==='function'){window.renderThreeLayer();return}\n if(state.tab==='compare'&&typeof window.renderLedgerCompare==='function'){window.renderLedgerCompare();return}"
if oldrender not in s: raise SystemExit('renderTab anchor missing')
s=s.replace(oldrender,newrender,1)
js=r'''
<script>
/* THREE_LAYER_OBSERVABILITY_V1_SCRIPT — GET only; Founder heads-up only */
(()=>{
 const READ='https://market-edge-founder-read.darkbishop43.workers.dev';
 const HOLD='https://market-edge-hold-observer.darkbishop43.workers.dev/current';
 const obs={exec:null,history:null,shadow:null,hold:null,error:null,updatedAt:null};
 const q=id=>document.getElementById(id), A=x=>Array.isArray(x)?x:[], N=v=>Number.isFinite(Number(v))?Number(v):null;
 const E=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const U=v=>String(v||'').toUpperCase();
 const tick=x=>String(x?.ticker??x?.marketTicker??x?.market_ticker??'');
 const side=x=>U(x?.side??x?.outcomeSide??x?.outcome??x?.yes_no??'');
 const ro=async u=>{const r=await fetch(u,{method:'GET',cache:'no-store',credentials:'omit',headers:{accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status+' '+u);return r.json()};
 const settlements=h=>[...A(h?.settlements),...A(h?.data?.settlements)];
 const providerRows=h=>[...A(h?.providerRows),...A(h?.fills),...A(h?.historicalFills),...A(h?.orders),...A(h?.historical_orders),...A(h?.data?.orders),...A(h?.data?.historical_orders)];
 function settlementFor(t){const rows=settlements(obs.history).filter(x=>tick(x)===t);return rows.length?rows[rows.length-1]:null}
 function finalDir(s){const v=U(s?.marketResult??s?.market_result??s?.result??s?.outcome);return v==='YES'||v==='NO'?v:v==='FLAT'||v==='TIE'?'FLAT':s?'UNKNOWN':'UNSETTLED'}
 function realizedFor(p){const ids=new Set([String(p?.entryOrderId||''),String(p?.exitOrderId||'')].filter(Boolean));const rows=providerRows(obs.history).filter(x=>ids.has(String(x?.order_id??x?.orderId??x?.id??'')));for(const r of rows){for(const k of ['realized_pnl','realizedPnl','profit_loss','pnl','pnlUsd','realizedPnlUsd']){const n=N(r?.[k]);if(n!==null)return n}}return null}
 function capture(a,p){if(Number(a?.fillCount||0)>0||Number(p?.filledCount||0)>0)return'FILLED';const st=U(a?.status);if(st.includes('NO_FILL'))return'NO_FILL';if(st.includes('PRE_SUBMIT')||st.includes('REQUALIFICATION_HOLD')||st.includes('LOCK_QUOTE_HOLD'))return'PRE_SUBMIT_HOLD';return'UNKNOWN'}
 function predictionClass(pred,fin){if(fin==='YES'||fin==='NO')return pred===fin?'CORRECT':pred==='YES'||pred==='NO'?'WRONG':'UNKNOWN';if(fin==='FLAT')return'FLAT';return'UNKNOWN'}
 function managementClass(cap,predClass,realized){if(cap!=='FILLED')return'—';if(predClass==='WRONG')return'PREDICTION_WRONG';if(predClass==='FLAT')return'FLAT';if(predClass!=='CORRECT')return'UNKNOWN';if(realized===null)return'UNKNOWN';if(realized>0)return'PREDICTION_CORRECT_MANAGEMENT_WIN';if(realized<0)return'PREDICTION_CORRECT_MANAGEMENT_LOSS';return'FLAT'}
 function rows(){const st=obs.exec?.state||{},ps=A(st.positions),attempts=A(st.attempts);return attempts.map(a=>{const p=ps.find(x=>String(x?.attemptNo)===String(a?.attemptNo)&&(!tick(a)||tick(x)===tick(a)))||ps.find(x=>tick(x)===tick(a))||null;const ticker=tick(a)||tick(p),pred=side(a)||side(p),set=settlementFor(ticker),fin=finalDir(set),cap=capture(a,p),pc=predictionClass(pred,fin),rz=p?realizedFor(p):null;return {series:a?.seriesId||p?.seriesId||st.seriesId||'—',attempt:a?.attemptNo??p?.attemptNo??'—',threshold:a?.threshold??st.threshold??'—',asset:a?.asset||p?.asset||'—',ticker,pred,entryScore:N(a?.liveScore??a?.observedScore??p?.entryScore),cap,fin,pc,noFill:cap==='NO_FILL'?(pc==='CORRECT'?'WOULD_HAVE_WON':pc==='WRONG'?'WOULD_HAVE_LOST':'UNKNOWN'):'—',entryPrice:N(p?.entryAverageFillPrice),entryTime:p?.filledAt||null,exitTime:p?.closedAt||null,exitPrice:N(p?.exitAverageFillPrice),exitReason:p?.exitReason||'—',realized:rz,management:managementClass(cap,pc,rz)}})}
 const cls=v=>/CORRECT|WOULD_HAVE_WON|MANAGEMENT_WIN/.test(v)?'triGood':/WRONG|WOULD_HAVE_LOST|MANAGEMENT_LOSS/.test(v)?'triBad':/UNKNOWN|UNSETTLED/.test(v)?'triUnknown':'triWarn';
 function summaries(rs){const groups=new Map();for(const r of rs){const k=String(r.series);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}return [...groups].map(([series,x])=>{const fills=x.filter(r=>r.cap==='FILLED'),nf=x.filter(r=>r.cap==='NO_FILL'),correct=fills.filter(r=>r.pc==='CORRECT').length,wrong=fills.filter(r=>r.pc==='WRONG').length,flat=fills.filter(r=>r.pc==='FLAT').length,den=correct+wrong;return {series,attempts:x.length,fills:fills.length,nofill:nf.length,fillRate:x.length?fills.length/x.length:null,correct,wrong,flat,accuracy:den?correct/den:null,nfWin:nf.filter(r=>r.noFill==='WOULD_HAVE_WON').length,nfLoss:nf.filter(r=>r.noFill==='WOULD_HAVE_LOST').length,nfUnknown:nf.filter(r=>r.noFill==='UNKNOWN').length,mgmtLoss:fills.filter(r=>r.management==='PREDICTION_CORRECT_MANAGEMENT_LOSS').length}})}
 window.renderThreeLayer=()=>{const el=q('tabPanel');if(!el)return;if(obs.error){el.innerHTML='<div class="empty">THREE-LAYER READ UNAVAILABLE · '+E(obs.error)+'</div>';return}const rs=rows(),sum=summaries(rs);const cards=sum.map(s=>'<div class="runCard"><div class="runName">RUN '+E(s.series)+'</div><div class="runGrid">'+[['ATTEMPTS',s.attempts],['FILLS',s.fills],['NO_FILL',s.nofill],['FILL RATE',s.fillRate===null?'—':(s.fillRate*100).toFixed(0)+'%'],['CORRECT FILLED',s.correct],['WRONG FILLED',s.wrong],['FLAT',s.flat],['DIRECTIONAL ACCURACY',s.accuracy===null?'—':(s.accuracy*100).toFixed(0)+'%'],['NO_FILL WOULD WIN',s.nfWin],['NO_FILL WOULD LOSE',s.nfLoss],['NO_FILL UNKNOWN',s.nfUnknown],['CORRECT / MGMT LOSS',s.mgmtLoss]].map(v=>'<div><div class="runK">'+E(v[0])+'</div><div class="runV">'+E(v[1])+'</div></div>').join('')+'</div></div>').join('');const heads=['RUN','ATT','THR','ASSET','TICKER','PRED','ENTRY SCORE','CAPTURE','FINAL','PREDICTION','NO_FILL CF','ENTRY PX','ENTRY TIME','EXIT TIME','EXIT PX','EXIT REASON','REALIZED','MANAGEMENT'];const body=rs.map(r=>'<tr>'+[r.series,r.attempt,r.threshold,r.asset,r.ticker,r.pred,r.entryScore===null?'—':r.entryScore.toFixed(3),r.cap,r.fin,r.pc,r.noFill,r.entryPrice===null?'—':r.entryPrice.toFixed(4),r.entryTime?new Date(r.entryTime).toLocaleString():'—',r.exitTime?new Date(r.exitTime).toLocaleString():'—',r.exitPrice===null?'—':r.exitPrice.toFixed(4),r.exitReason,r.realized===null?'UNKNOWN':r.realized.toFixed(4),r.management].map((v,i)=>'<td class="'+(i===9||i===10||i===17?cls(String(v)):'')+'">'+E(v)+'</td>').join('')+'</tr>').join('');el.innerHTML='<div class="threeLayerWrap"><div class="threeHead"><div><div class="threeTitle">PREDICTION / CAPTURE / MANAGEMENT</div><div class="threeSub">EXACT-TICKER SETTLEMENT ONLY · COUNTERFACTUALS NEVER INFERRED · FOUNDER READ ONLY</div></div><span class="badge live">ZERO AUTO AUTHORITY</span></div><div class="runCards">'+(cards||'<div class="holdEmpty">No persisted governed attempts available.</div>')+'</div>'+(rs.length?'<table class="triTbl"><thead><tr>'+heads.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table>':'<div class="empty">No governed attempt records available.</div>')+'</div>'};
 function exactScores(p){const opportunities=A(obs.shadow?.opportunities),t=String(p?.ticker||''),owned=U(p?.side),same=opportunities.find(o=>tick(o)===t&&side(o)===owned),opp=opportunities.find(o=>tick(o)===t&&side(o)&&side(o)!==owned);let sameScore=N(same?.score);if(sameScore===null)sameScore=N(p?.currentScore);return {same:sameScore,opp:N(opp?.score)}}
 function thesis(p){const x=exactScores(p),entry=N(p?.entryScore),same=x.same,opp=x.opp;let light='YELLOW',reason='CURRENT EVIDENCE INCOMPLETE';if(same!==null&&same<=.20){light='RED';reason='.20 EXIT CONDITION MET'}else if(same!==null&&opp!==null&&opp>=same+.10){light='RED';reason='OPPOSITE SIDE NOW STRONGER'}else if(same===null){light='YELLOW';reason='CURRENT SAME-SIDE SCORE UNAVAILABLE'}else if(opp===null){light='YELLOW';reason='OPPOSITE-SIDE SCORE UNAVAILABLE'}else if((entry!==null&&same<=entry-.15)||Math.abs(same-opp)<.10){light='YELLOW';reason='THESIS WEAKENED / SIDES COMPETITIVE'}else{light='GREEN';reason='SAME-CONTRACT EVIDENCE ALIGNED'}return {light,reason,entry,same,opp,sameDelta:entry!==null&&same!==null?same-entry:null}}
 function paintThesis(){const ps=A(obs.hold?.positions);document.querySelectorAll('.holdCard').forEach(card=>card.querySelector('.thesisStrip')?.remove());for(const p of ps){const card=[...document.querySelectorAll('.holdCard')].find(c=>String(c.querySelector('.holdTicker')?.textContent||'').trim()===String(p.ticker||''));if(!card)continue;const t=thesis(p),lc=t.light.toLowerCase();card.insertAdjacentHTML('beforeend','<div class="thesisStrip"><div class="thesisTop"><span class="thesisLight '+lc+'">● '+t.light+'</span><span class="thesisReason">'+E(t.reason)+'</span><span class="thesisExact">EXACT TICKER ONLY</span></div><div class="thesisGrid"><div><div class="holdK">ENTRY SCORE</div><div class="holdV">'+(t.entry===null?'—':t.entry.toFixed(3))+'</div></div><div><div class="holdK">CURRENT '+E(p.side)+'</div><div class="holdV">'+(t.same===null?'—':t.same.toFixed(3))+'</div></div><div><div class="holdK">CHANGE SINCE ENTRY</div><div class="holdV">'+(t.sameDelta===null?'—':(t.sameDelta>=0?'+':'')+t.sameDelta.toFixed(3))+'</div></div><div><div class="holdK">CURRENT OPPOSITE</div><div class="holdV">'+(t.opp===null?'—':t.opp.toFixed(3))+'</div></div><div><div class="holdK">OPPOSITE CHANGE</div><div class="holdV">NOT RETAINED</div></div></div><div class="thesisNote">FOUNDER HEADS-UP ONLY · NO AUTO ACTION · NO EXIT / ENTRY / HOLD AUTHORITY</div></div>')}}
 async function refresh(){try{const [exec,history,shadow,hold]=await Promise.all([ro(READ+'/execution-test-state'),ro(READ+'/forensic-provider-history?limit=200'),ro(READ+'/shadow-state'),ro(HOLD)]);obs.exec=exec;obs.history=history;obs.shadow=shadow;obs.hold=hold;obs.error=null;obs.updatedAt=new Date().toISOString();if(document.querySelector('.tabs button[data-tab="triage"]')?.classList.contains('on'))window.renderThreeLayer();paintThesis()}catch(e){obs.error=String(e?.message||e);if(document.querySelector('.tabs button[data-tab="triage"]')?.classList.contains('on'))window.renderThreeLayer()}}
 refresh();setInterval(refresh,10000);setInterval(paintThesis,1000);
})();
</script>
'''
if 'THREE_LAYER_OBSERVABILITY_V1_SCRIPT' not in s:
    s=s.replace('</body>',js+'\n</body>',1)
p.write_text(s)
print('THREE_LAYER_COCKPIT_PATCHED=YES')
