const FEED='https://market-edge-lab.darkbishop43.workers.dev/api/state';
const GAMMA='https://gamma-api.polymarket.com';
const FS=await import('node:fs/promises');
const path=await import('node:path');
const ROOT='market-edge-lab/siblings/state';
const MAX_STAKE=5,MAX_OPEN=6,MAX_HOLD_MS=5*60*1000,COOLDOWN_MS=5*60*1000;
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
const arr=v=>{try{return typeof v==='string'?JSON.parse(v):v}catch{return null}};
const question=o=>o.question||o.title||o.marketQuestion||o.slug||'Unknown market';
const asset=o=>o.asset||(/ethereum|\beth\b/i.test(question(o))?'ETH':'BTC');
const score=o=>Number(o.score??o.signalScore??0),edge=o=>Number(o.edge??0),move=o=>Number(o.move??o.assetMove??o.btcMove??o.ethMove??0),price=o=>Number(o.positionPrice??o.yesPrice??o.yes??o.price??0),marketId=o=>String(o.id??o.marketId??o.conditionId??o.slug??question(o));
function side(o){if(o.side)return o.side;if(o.bear===true)return'BELOW';const q=question(o).toLowerCase(),dn=/\b(below|lower|under|down|fall|drop|decrease)\b/.test(q)||q.includes('↓'),up=/\b(above|higher|over|up|rise|gain|increase)\b/.test(q)||q.includes('↑');return dn&&!up?'BELOW':up&&!dn?'ABOVE':'UNKNOWN'}
const oppKey=o=>marketId(o)+':'+(o.positionOutcome||'YES')+':'+side(o);
async function j(url){const r=await fetch(url,{headers:{'user-agent':'NFE-OS-Market-Edge-Paper-Research'}});if(!r.ok)throw Error(`${r.status} ${url}`);return r.json()}
function parsePrices(m){const p=arr(m.outcomePrices),outs=arr(m.outcomes);if(!Array.isArray(p)||p.length<2)return null;let yi=0,ni=1;if(Array.isArray(outs)){const y=outs.findIndex(x=>String(x).toLowerCase()==='yes'),n=outs.findIndex(x=>String(x).toLowerCase()==='no');if(y>=0&&n>=0){yi=y;ni=n}}const yes=Number(p[yi]),no=Number(p[ni]);return Number.isFinite(yes)&&Number.isFinite(no)?{yes,no}:null}
function eligibleMarket(m,ev,p){if(m.closed===true||ev?.closed===true||m.active===false||ev?.active===false||m.acceptingOrders===false)return false;const end=m.endDate||m.endDateIso||ev?.endDate||ev?.endDateIso;if(end){const x=Date.parse(end);if(Number.isFinite(x)&&x<=Date.now())return false}return !(p.yes<=.01||p.yes>=.99||p.no<=.01||p.no>=.99)}
function inferDirection(q){q=String(q||'').toLowerCase();const a=q.includes('bitcoin')||/\bbtc\b/.test(q)?'BTC':q.includes('ethereum')||/\beth\b/.test(q)?'ETH':null;if(!a)return null;const dn=/\b(below|lower|under|down|fall|drop|decrease)\b/.test(q)||q.includes('↓'),up=/\b(above|higher|over|up|rise|gain|increase)\b/.test(q)||q.includes('↑');if(dn===up)return null;return{asset:a,side:dn?'BELOW':'ABOVE'}}
function scored(dir,p,mv,base){const dm=dir==='BELOW'?-mv:mv,fair=clamp(p+dm*18,.02,.98),ed=fair-p,sc=clamp(.5+ed*4,0,1);return{...base,side:dir,bear:dir==='BELOW',move:mv,positionPrice:p,fair,edge:ed,score:sc}}
async function discoverQuery(q){const s=await j(`${GAMMA}/public-search?q=${encodeURIComponent(q)}`);const evs=(s.events||[]).slice(0,14);return(await Promise.all(evs.map(async e=>{try{return await j(`${GAMMA}/events/${e.id}`)}catch{return null}}))).filter(Boolean)}
async function buildOpportunities(snapshot){const base=(snapshot?.opportunities||snapshot?.eligible||snapshot?.candidates||[]).map(o=>({...o,side:side(o),positionOutcome:o.positionOutcome||'YES',source:o.source||'BASELINE_FEED'}));const moves=snapshot?.moves||{};const map=new Map(base.map(o=>[oppKey(o),o]));const qs=['bitcoin below','bitcoin down','bitcoin under','What price will Bitcoin hit','ethereum below','ethereum down','ethereum under','What price will Ethereum hit'];
  const groups=(await Promise.all(qs.map(discoverQuery))).flat();
  for(const ev of groups)for(const m of(ev.markets||[])){const q=[ev.title,m.question,m.groupItemTitle,m.slug].filter(Boolean).join(' — '),dir=inferDirection(q),p=parsePrices(m);if(!dir||dir.side!=='BELOW'||!p||!eligibleMarket(m,ev,p))continue;const id=String(m.id||m.conditionId||m.slug),mv=Number(moves[dir.asset]||0),o=scored('BELOW',p.yes,mv,{id,question:q,asset:dir.asset,positionOutcome:'YES',yes:p.yes,no:p.no,source:'EXPLICIT_BELOW_CONTRACT'});map.set(oppKey(o),o)}
  for(const o of base.filter(x=>side(x)==='ABOVE').slice(0,16)){try{const m=await j(`${GAMMA}/markets/${encodeURIComponent(marketId(o))}`),p=parsePrices(m);if(!p||!eligibleMarket(m,null,p))continue;const outs=arr(m.outcomes);if(Array.isArray(outs)&&!(outs.some(x=>String(x).toLowerCase()==='yes')&&outs.some(x=>String(x).toLowerCase()==='no')))continue;const a=asset(o),mv=Number(moves[a]||move(o)||0),n=scored('BELOW',p.no,mv,{id:marketId(o),question:`DOWNSIDE (NO) · ${question(o)}`,asset:a,positionOutcome:'NO',yes:p.yes,no:p.no,source:'VALIDATED_NO_SIDE'});map.set(oppKey(n),n)}catch{}}
  return[...map.values()].sort((a,b)=>score(b)-score(a));
}
function decision(lab,o,os){const sc=score(o),ed=edge(o),mv=Math.abs(move(o));if(lab==='payne_method')return sc>=.80&&ed>0&&mv>=.002?'ENTER':'WAIT';const a=asset(o),sd=side(o),peers=os.filter(x=>asset(x)===a&&side(x)===sd).sort((x,y)=>score(y)-score(x)),rank=Math.max(1,peers.findIndex(x=>oppKey(x)===oppKey(o))+1),opp=os.filter(x=>asset(x)===a&&side(x)!==sd).sort((x,y)=>score(y)-score(x))[0],oppScore=opp?score(opp):null;return sc>=.80&&ed>0&&rank===1&&(oppScore==null||sc>=oppScore+.05)?'ENTER':'WAIT'}
async function load(lab){const f=path.join(ROOT,lab+'.json');try{return JSON.parse(await FS.readFile(f,'utf8'))}catch{return{mode:'PAPER_ONLY',lab,balance:100,realizedPnl:0,positions:[],ledger:[],trades:0,createdAt:new Date().toISOString(),executor:'GITHUB_ACTIONS_CLOUD_V1'}}}
async function save(lab,s){await FS.mkdir(ROOT,{recursive:true});await FS.writeFile(path.join(ROOT,lab+'.json'),JSON.stringify(s,null,2)+'\n')}
function lastExit(s,k){return(s.ledger||[]).slice().reverse().find(x=>x.type==='PAPER_EXIT'&&x.oppKey===k)}
function close(s,p,o,reason){const ex=o?price(o):p.entry;if(!(ex>0)||!(p.entry>0))return false;const heldMs=Date.now()-Date.parse(p.entryTs||p.ts),value=(p.stake/p.entry)*ex,pnl=value-p.stake;s.balance+=value;s.realizedPnl+=pnl;s.trades=(s.trades||0)+1;s.ledger.push({type:'PAPER_EXIT',lab:s.lab,ts:new Date().toISOString(),entryTs:p.entryTs||p.ts,oppKey:p.oppKey,marketId:p.marketId,question:p.question,asset:p.asset,side:p.side,positionOutcome:p.positionOutcome,stake:p.stake,entry:p.entry,exit:ex,score:p.score,edge:p.edge,heldMs,reason,pnl});s.positions=s.positions.filter(x=>x.oppKey!==p.oppKey);return true}
function open(s,o){const en=price(o);if(!(en>0)||en>=1)return false;const stake=Math.min(MAX_STAKE,s.balance);if(stake<=0)return false;const ts=new Date().toISOString(),p={oppKey:oppKey(o),marketId:marketId(o),question:question(o),asset:asset(o),side:side(o),positionOutcome:o.positionOutcome||'YES',stake,entry:en,score:score(o),edge:edge(o),entryTs:ts,ts};s.balance-=stake;s.positions.push(p);s.ledger.push({type:'PAPER_ENTRY',lab:s.lab,ts,...p});return true}
async function runLab(lab,os){const s=await load(lab);s.positions=s.positions||[];s.ledger=s.ledger||[];let changed=false;for(const p of[...s.positions]){const o=os.find(x=>oppKey(x)===p.oppKey),held=Date.now()-Date.parse(p.entryTs||p.ts);if(held>=MAX_HOLD_MS)changed=close(s,p,o,'max_hold')||changed;else if(!o)changed=close(s,p,null,'market_missing')||changed;else if(decision(lab,o,os)!=='ENTER')changed=close(s,p,o,'decision_exit')||changed}const keys=new Set(s.positions.map(p=>p.oppKey));for(const o of os){if(s.positions.length>=MAX_OPEN)break;const k=oppKey(o);if(keys.has(k)||decision(lab,o,os)!=='ENTER')continue;const last=lastExit(s,k);if(last&&Date.now()-Date.parse(last.ts)<COOLDOWN_MS)continue;if(open(s,o)){keys.add(k);changed=true}}if(changed){s.updatedAt=new Date().toISOString();s.executor='GITHUB_ACTIONS_CLOUD_V1';await save(lab,s);console.log(lab,'changed',s.balance,s.trades,s.positions.length)}else console.log(lab,'no change')}
const snapshot=await j(FEED),os=await buildOpportunities(snapshot);console.log('opportunities',os.length);await runLab('nfe_reasoning',os);await runLab('payne_method',os);